#!/usr/bin/env bash
# Write a Bash script that transfers a file from our client to a server:

PATH_TO_FILE=$1
IP=$2
USERNAME=$3
PATH_TO_SSH_KEY=$4

scp -o StrictHostKeyChecking=no "$3"@"$2:~/" -i "$4" "$1"
