#!/usr/bin/env bash
# Web servers are the piece of software generating and serving HTML pages, let’s install one!

sudo update sudo apt-get update
sudo apt-get install -y nginx

# Configure Nginx to listen on port 80
sed -i 's/^listen\s*80\s*;$/listen 80;/g' /etc/nginx/sites-available/default

# Create a temporary HTML file containing "Hello World!"
echo "Hello World!" > /tmp/index.html

# Move the HTML file to Nginx default document root
cp /tmp/index.html /var/www/html/index.html

#Restart nginx restart
service nginx restart
