#!/usr/bin/env bash
# This script is displaying "Best School" 10 times, also display hi on the 9th iteraton

i=1
while ((i<=10))
do
	if [ $i == 9 ]
	then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	((i++))
done
exit 0
