#!/bin/bash
#For the containers that you are given in this project as well as the checker, everything is run under the root user, which has the ability to run anything as another user.

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <username>"
    exit 1
fi

# Run the whoami command under the specified user
sudo -u "$1" whoami
